name: 'require-rebase'
on:
  pull_request:

env:
  BASE: main
  ORIGIN: origin

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch
        run: |
          git fetch ${{ env.ORIGIN }} ${{ env.BASE }}

      - name: Check
        uses: ./
        with:
          base: ${{ env.BASE }}
          origin: ${{ env.ORIGIN }}
